penilaian/urls.py
from os import name
from django.views.static import serve
from django.urls import path
from . import views
from webfisika import settings
from django.conf.urls.static import static

urlpatterns = [
    path('edit_data/<pk>/', views.EditDataDiriView.as_view(), name='edit_data'),
    ######### End Edit Data User #########
    path('upload_berkas_jurnal/', views.UploadBerkasJurnalView.as_view(), name='upload_berkas_jurnal'),
    path('upload_berkas_prosiding/', views.UploadBerkasProsidingView.as_view(), name='upload_berkas_prosiding'),
    path('upload_berkas_buku/', views.UploadBerkasBukuView.as_view(), name='upload_berkas_buku'),
    path('upload_berkas_haki/', views.UploadBerkasHakiView.as_view(), name='upload_berkas_haki'),
    ######### End Upload #########
    path('histori_pengajuan/jurnal/<page>/', views.ListBerkasJurnalView.as_view(), name='list_berkas_jurnal'),
    path('histori_pengajuan/prosiding/<page>/', views.ListBerkasProsidingView.as_view(), name='list_berkas_prosiding'),
    path('histori_pengajuan/buku/<page>/', views.ListBerkasBukuView.as_view(), name='list_berkas_buku'),
    path('histori_pengajuan/haki/<page>/', views.ListBerkasHakiView.as_view(), name='list_berkas_haki'),
    ######### End List Pengajuan #########
    path('histori_pengajuan/jurnal/detail/<pk>/', views.DetailBerkasJurnalView.as_view(), name='detail_berkas_jurnal'),
    path('histori_pengajuan/prosiding/detail/<pk>/', views.DetailBerkasProsidingView.as_view(), name='detail_berkas_prosiding'),
    path('histori_pengajuan/buku/detail/<pk>/', views.DetailBerkasBukuView.as_view(), name='detail_berkas_buku'),
    path('histori_pengajuan/haki/detail/<pk>/', views.DetailBerkasHakiView.as_view(), name='detail_berkas_haki'),
    ######### End Detail Berkas #########
    path('histori_pengajuan/jurnal/edit/<pk>/', views.EditBerkasJurnalView.as_view(), name='edit_berkas_jurnal'),
    path('histori_pengajuan/prosiding/edit/<pk>/', views.EditBerkasProsidingView.as_view(), name='edit_berkas_prosiding'),
    path('histori_pengajuan/buku/edit/<pk>/', views.EditBerkasBukuView.as_view(), name='edit_berkas_buku'),
    path('histori_pengajuan/haki/edit/<pk>/', views.EditBerkasHakiView.as_view(), name='edit_berkas_haki'),
    ######### End Edit Berkas #########
    path('histori_pengajuan/jurnal/plagiasi_linieritas/<pk>/', views.PlagiasiLinieritasView.as_view(), name='plagiasi'),
    path('histori_pengajuan/jurnal/plagiasi_linieritas/edit/<pk>/', views.EditPlagiasiLinieritasView.as_view(), name='edit_plagiasi'),
    path('histori_pengajuan/prosiding/plagiasi_linieritas/<pk>/', views.PlagiasiLinieritasProsidingView.as_view(), name='plagiasi_prosiding'),
    path('histori_pengajuan/prosiding/plagiasi_linieritas/edit/<pk>/', views.EditPlagiasiLinieritasProsidingView.as_view(), name='edit_plagiasi_prosiding'),
    ######### End Plagiasi #########
    path('histori_pengajuan/jurnal/verifikasi/<pk>/', views.VerifikasiBerkasJurnalView.as_view(), name='verifikasi_berkas_jurnal'),
    path('histori_pengajuan/prosiding/verifikasi/<pk>/', views.VerifikasiBerkasProsidingView.as_view(), name='verifikasi_berkas_prosiding'),
    path('histori_pengajuan/buku/verifikasi/<pk>/', views.VerifikasiBerkasBukuView.as_view(), name='verifikasi_berkas_buku'),
    path('histori_pengajuan/haki/verifikasi/<pk>/', views.VerifikasiBerkasHakiView.as_view(), name='verifikasi_berkas_haki'),
    ######### End Verifikasi Berkas #########
    # R1 #
    path('penilaian_jurnal/R1/<pk>/', views.PenilaianBerkasJurnalView.as_view(), name='penilaian_jurnal'),
    path('penilaian_prosiding/R1/<pk>/', views.PenilaianBerkasProsidingView.as_view(), name='penilaian_prosiding'),
    path('penilaian_buku/R1/<pk>/', views.PenilaianBerkasBukuView.as_view(), name='penilaian_buku'),
    path('penilaian_haki/R1/<pk>/', views.PenilaianBerkasHakiView.as_view(), name='penilaian_haki'),
    # R2 #
    path('penilaian_jurnal/R2/<pk>/', views.PenilaianBerkasJurnal2View.as_view(), name='penilaian_jurnal2'),
    path('penilaian_prosiding/R2/<pk>/', views.PenilaianBerkasProsiding2View.as_view(), name='penilaian_prosiding2'),
    path('penilaian_buku/R2/<pk>/', views.PenilaianBerkasBuku2View.as_view(), name='penilaian_buku2'),
    path('penilaian_haki/R2/<pk>/', views.PenilaianBerkasHaki2View.as_view(), name='penilaian_haki2'),
    ######### End Penilaian #########
    # R1 #
    path('rekap_jurnal/R1/<slug>/',views.HasilPenilaianJurnalView.as_view(), name='rekap_jurnal'),
    path('rekap_prosiding/R1/<slug>/',views.HasilPenilaianProsidingView.as_view(), name='rekap_prosiding'),
    path('rekap_buku/R1/<slug>/',views.HasilPenilaianBukuView.as_view(), name='rekap_buku'),
    path('rekap_haki/R1/<slug>/',views.HasilPenilaianHakiView.as_view(), name='rekap_haki'),
    # R2 #
    path('rekap_jurnal/R2/<slug>/',views.HasilPenilaianJurnal2View.as_view(), name='rekap_jurnal2'),
    path('rekap_prosiding/R2/<slug>/',views.HasilPenilaianProsiding2View.as_view(), name='rekap_prosiding2'),
    path('rekap_buku/R2/<slug>/',views.HasilPenilaianBuku2View.as_view(), name='rekap_buku2'),
    path('rekap_haki/R2/<slug>/',views.HasilPenilaianHaki2View.as_view(), name='rekap_haki2'),
    # Gabungan R1 dan R2 #
    path('rekap_jurnal/<slug>/', views.HasilPenilaianBerkasJurnalGabunganView.as_view(), name='gabungan_jurnal'),
    path('rekap_prosiding/<slug>/', views.HasilPenilaianBerkasProsidingGabunganView.as_view(), name='gabungan_prosiding'),
    path('rekap_buku/<slug>/', views.HasilPenilaianBerkasBukuGabunganView.as_view(), name='gabungan_buku'),
    path('rekap_haki/<slug>/', views.HasilPenilaianBerkasHakiGabunganView.as_view(), name='gabungan_haki'),
    ######### End of Hasil Rekap #########
    path('tambah_penulis/', views.PenulisLainView.as_view(), name='tambah_penulis'),
    ######### End of Tambah Penulis #########
    path('list_penilaian_jurnal/<page>/', views.ListReviewerJurnalView.as_view(), name='list_penilaian_jurnal'),
    path('list_penilaian_prosiding/<page>/', views.ListReviewerProsidingView.as_view(), name='list_penilaian_prosiding'),
    path('list_penilaian_buku/<page>/', views.ListReviewerBukuView.as_view(), name='list_penilaian_buku'),
    path('list_penilaian_haki/<page>/', views.ListReviewerHakiView.as_view(), name='list_penilaian_haki'),
    ######### End of Tabel Penilaian #########
    # R1 #
    path('penilaian_jurnal/edit/R1/<slug>/', views.PenilaianBerkasJurnalEditView.as_view(), name='edit_penilaian_jurnal'),
    path('penilaian_prosiding/edit/R1/<slug>/', views.PenilaianBerkasProsidingEditView.as_view(), name='edit_penilaian_prosiding'),
    path('penilaian_buku/edit/R1/<slug>/', views.PenilaianBerkasBukuEditView.as_view(), name='edit_penilaian_buku'),
    path('penilaian_haki/edit/R1/<slug>/', views.PenilaianBerkasHakiEditView.as_view(), name='edit_penilaian_haki'),
    # R2 #
    path('penilaian_jurnal/edit/R2/<slug>/', views.PenilaianBerkasJurnal2EditView.as_view(), name='edit_penilaian_jurnal2'),
    path('penilaian_prosiding/edit/R2/<slug>/', views.PenilaianBerkasProsiding2EditView.as_view(), name='edit_penilaian_prosiding2'),
    path('penilaian_buku/edit/R2/<slug>/', views.PenilaianBerkasBuku2EditView.as_view(), name='edit_penilaian_buku2'),
    path('penilaian_haki/edit/R2/<slug>/', views.PenilaianBerkasHaki2EditView.as_view(), name='edit_penilaian_haki2'),
    ######### End of Edit Penilaian #########
    path('error/penilaian_belum_ada', views.ErrorMessage.as_view(), name='error_message'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ubah_data_user/', views.UserEditView.as_view(), name='ubah_data_user'),
    path('signup/', views.UserRegisterView.as_view(), name='register'),
    path('password/', views.PasswordChangeView.as_view(), name='ubah_password'),   
]

webfisika/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexHomeView.as_view(), name='home'),
    # path('', views.ComingSoon.as_view(), name='home'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('success/', views.Success.as_view(), name = 'success'),
    path('penilaian/', include(('penilaian.urls', 'penilaian'), namespace='penilaian')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

penilaian/templates/penilaian/edit_penilaian_haki2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Penilaian Berkas Haki</title>
    {% include 'snippets/style.html' %}
</head>
<body>
    {% include 'snippets/navbar.html' %}
    <section id="portfolio" class="portfolio">
        <div class="container" data-aos="fade-up">
          <br>
          <div class="section-title">
            <h2 class="text-white">Edit Penilaian Berkas Haki</h2>
          </div>
        </div>
    </section><!-- End Portfolio Section -->
    <div class="container">
        <br>
        <a class="float-right btn btn-outline-warning btn-sm" data-toggle="modal" data-target="#KetentuanHaki" data-aos="zoom-in">Ketentuan</a>
        <br>
        <form method="POST" enctype="multipart/form-data" data-aos="zoom-in">
            <div class="form-group">
                {% csrf_token %}
                <br>
                {{form.as_p}}
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>
    </div>
    {% include 'snippets/modals.html' %}
    {% include 'snippets/script.html' %}
</body>
</html>

penilaian/templates/penilaian/list_reviewer_jurnal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daftar Status Penilaian</title>
    {% include 'snippets/style.html' %}
</head>
<body>
  {% include 'snippets/navbar.html' %}
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">
        <br>
        <div class="section-title">
          <h2 class="text-white">Daftar Status Penilaian Jurnal</h2>
          <p class="text-white">Daftar Jurnal yang Sudah dan Belum Dinilai</p>
        </div>
        <ul id="portfolio-flters" class="pilihan d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
          <li><a class="pilihan text-white" href="{% url 'penilaian:list_penilaian_jurnal' 1 %}">Jurnal</a></li>
          <li><a class="pilihan text-white" href="{% url 'penilaian:list_penilaian_prosiding' 1 %}">Prosiding</a></li>
          <li><a class="pilihan text-white" href="{% url 'penilaian:list_penilaian_buku' 1 %}">Buku</a></li>
          <li><a class="pilihan text-white" href="{% url 'penilaian:list_penilaian_haki' 1 %}">HaKI</a></li>
        </ul>
      </div>
    </section><!-- End Portfolio Section -->
    <br>
    
    <div class="container" data-aos="zoom-in">
      <form class="d-flex justify-content-center form-inline" method="GET">
        <input class="form-control mr-sm-2" name="search" type="search" placeholder="Cari Judul Artikel" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Cari</button>
      </form>
      <div class="scrollmenu">
        <table class="table" data-aos="zoom-in">
          <thead>
            <tr>
              <th>Judul Artikel</th>
              <th>Reviewer</th>
              <th>Nilai/Edit</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for berkas in list_reviewer_jurnal %}
              {% if berkas.is_verificated %}
                {% if user.id == berkas.reviewer.reviewer.id %}
                    <tr>
                        <td style="width: 30%;"><a href="{% url 'penilaian:detail_berkas_jurnal' berkas.pk%}" class="judul-artikel" target="_bl">{{berkas.judul_artikel}}</a></td>
                        {% if berkas.reviewer == None %}
                          <td>Belum Ada</td>
                        {% elif berkas.reviewer != None %}
                          <td>{{berkas.reviewer}}</td>
                        {% endif %}
                        <td>
                          {% if user.id == berkas.reviewer.reviewer.id %}
                            <a class="btn btn-primary" href="{% url 'penilaian:penilaian_jurnal' berkas.pk %}">Nilai</a>
                            {% for berkus in list_berkas %}
                              {% if berkas.id == berkus.jurnal.id %}
                                <a class="btn btn-warning" href="{% url 'penilaian:edit_penilaian_jurnal' berkas.slug %}">Edit</a>
                              {% endif %}
                            {% endfor %}
                          {% endif %}
                        <td>
                          {% for berkus in list_berkas %}
                            {% if berkas.id == berkus.jurnal.id %}
                              <button disabled type="button" class="btn btn-success">Sudah Dinilai</button>
                            {% endif %}
                          {% endfor %}
                        </td>
                    </tr>
                {% endif %}
                {% if user.id == berkas.reviewer_2.reviewer.id %}
                    <tr>
                      <td style="width: 30%;"><a href="{% url 'penilaian:detail_berkas_jurnal' berkas.pk%}" class="judul-artikel" target="_bl">{{berkas.judul_artikel}}</a></td>
                        {% if berkas.reviewer_2 == None %}
                          <td>Belum Ada</td>
                        {% elif berkas.reviewer_2 != None %}
                          <td>{{berkas.reviewer_2}}</td>
                        {% endif %}
                        <td>
                          {% if user.id == berkas.reviewer_2.reviewer.id %}
                            <a class="btn btn-primary" href="{% url 'penilaian:penilaian_jurnal2' berkas.pk %}">Nilai</a>
                            {% for berkus2 in list_berkas_2 %}
                              {% if berkas.id == berkus2.jurnal.id %}
                                <a class="btn btn-warning" href="{% url 'penilaian:edit_penilaian_jurnal2' berkas.slug %}">Edit</a>
                              {% endif %}
                            {% endfor %}
                          {% endif %}
                        <td>
                          {% for berkus2 in list_berkas_2 %}
                            {% if berkas.id == berkus2.jurnal.id %}
                              <button disabled type="button" class="btn btn-success">Sudah Dinilai</button>
                            {% endif %}
                          {% endfor %}
                        </td>
                    </tr>
                {% endif %}
                {% if user.is_superuser %}
                    <tr>
                      <td style="width: 30%;"><a href="{% url 'penilaian:detail_berkas_jurnal' berkas.pk%}" class="judul-artikel" target="_blank">{{berkas.judul_artikel}}</a></td>
                        <td>
                          {% if berkas.reviewer == None %}
                            Belum Ada
                          {% elif berkas.reviewer != None %}
                            {{berkas.reviewer}}
                          {% endif %}
                          {% if berkas.reviewer_2 == None %}
                            <br> Belum Ada
                          {% elif berkas.reviewer_2 != None %}
                            <br> {{berkas.reviewer_2}}
                          {% endif %}
                        </td>
                        <td>
                          {% if user.is_superuser %}
                            {% if berkas.reviewer != None %}
                              <a class="btn btn-primary" href="{% url 'penilaian:penilaian_jurnal' berkas.pk %}">Nilai</a>
                              {% for berkus in list_berkas %}
                                {% if berkas.id == berkus.jurnal.id %}
                                  <a class="btn btn-warning" href="{% url 'penilaian:edit_penilaian_jurnal' berkas.slug %}">Edit<a>
                                {% endif %}
                              {% endfor %}
                            {% endif %}
                            <div class="spacing"></div>
                            {% if berkas.reviewer_2 != None %}
                              <a class="btn btn-primary" href="{% url 'penilaian:penilaian_jurnal2' berkas.pk %}">Nilai</a>
                              {% for berkus2 in list_berkas_2 %}
                                {% if berkas.id == berkus2.jurnal.id %}
                                  <a class="btn btn-warning" href="{% url 'penilaian:edit_penilaian_jurnal2' berkas.slug %}">Edit</a>
                                {% endif %}
                              {% endfor %}
                            {% endif %}
                          {% endif %}
                        <td>
                          {% for berkus in list_berkas %}
                            {% if berkas.id == berkus.jurnal.id %}
                              <button disabled class="btn btn-success">Sudah Dinilai (R1)</button>
                            {% endif %}
                          {% endfor %}
                          <div class="spacing"></div>
                          {% for berkus2 in list_berkas_2 %}
                            {% if berkas.id == berkus2.jurnal.id %}
                              <button disabled class="btn btn-success">Sudah Dinilai (R2)</button>
                            {% endif %}
                          {% endfor %}
                        </td>
                    </tr>
                {% endif %}
              {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="pagination d-flex justify-content-center">
        {% if page_obj.has_previous %}
          <a href="{% url 'penilaian:list_penilaian_jurnal' page_obj.previous_page_number %}">&laquo;</a>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <span class="active">
              {{i}}
            </span>
          {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
            <a href="{% url 'penilaian:list_penilaian_jurnal' i %}">
              {{i}}
            </a>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <a href="{% url 'penilaian:list_penilaian_jurnal' page_obj.next_page_number %}">&raquo;</a>
        {% endif %}
      </div>
    </div>
    
      
    {% include 'snippets/script.html' %}
</body>
</html>

penilaian/templates/penilaian/list_reviewer_prosiding.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daftar Status Penilaian</title>
    {% include 'snippets/style.html' %}
</head>
<body>
  {% include 'snippets/navbar.html' %}
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">
        <br>
        <div class="section-title">
          <h2 class="text-white">Daftar Status Penilaian Prosiding</h2>
          <p class="text-white">Daftar Prosiding yang Sudah dan Belum Dinilai</p>
        </div>
        <ul id="portfolio-flters" class="pilihan d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
          <li><a class="pilihan text-white" href="{% url 'penilaian:list_penilaian_jurnal' 1 %}">Jurnal</a></li>
          <li><a class="pilihan text-white" href="{% url 'penilaian:list_penilaian_prosiding' 1 %}">Prosiding</a></li>
          <li><a class="pilihan text-white" href="{% url 'penilaian:list_penilaian_buku' 1 %}">Buku</a></li>
          <li><a class="pilihan text-white" href="{% url 'penilaian:list_penilaian_haki' 1 %}">HaKI</a></li>
        </ul>
      </div>
    </section><!-- End Portfolio Section -->
    <br>
    
    <div class="container" data-aos="zoom-in">
      <form class="d-flex justify-content-center form-inline" method="GET">
        <input class="form-control mr-sm-2" name="search" type="search" placeholder="Cari Judul Artikel" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Cari</button>
      </form>
      <div class="scrollmenu">
        <table class="table" data-aos="zoom-in">
          <thead>
            <tr>
              <th>Judul Artikel</th>
              <th>Reviewer</th>
              <th>Nilai/Edit</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for berkas in list_reviewer_prosiding %}
              {% if berkas.is_verificated %}
                {% if user.id == berkas.reviewer.reviewer.id %}
                    <tr>
                        <td style="width: 30%;"><a href="{% url 'penilaian:detail_berkas_prosiding' berkas.pk%}" class="judul-artikel" target="_blank">{{berkas.judul_artikel}}</a></td>
                        {% if berkas.reviewer == None %}
                          <td>Belum Ada</td>
                        {% elif berkas.reviewer != None %}
                          <td>{{berkas.reviewer}}</td>
                        {% endif %}
                        <td>
                          {% if user.id == berkas.reviewer.reviewer.id %}
                            <a class="btn btn-primary" href="{% url 'penilaian:penilaian_prosiding' berkas.pk %}">Nilai</a>
                            {% for berkus in list_berkas %}
                              {% if berkas.id == berkus.prosiding.id %}
                                <a class="btn btn-warning" href="{% url 'penilaian:edit_penilaian_prosiding' berkas.slug %}">Edit</a>
                              {% endif %}
                            {% endfor %}
                          {% endif %}
                        <td>
                          {% for berkus in list_berkas %}
                            {% if berkas.id == berkus.prosiding.id %}
                              <button disabled type="button" class="btn btn-success">Sudah Dinilai</button>
                            {% endif %}
                          {% endfor %}
                        </td>
                    </tr>
                {% endif %}
                {% if user.id == berkas.reviewer_2.reviewer.id %}
                    <tr>
                        <td style="width: 30%;"><a href="{% url 'penilaian:detail_berkas_prosiding' berkas.pk%}" class="judul-artikel" target="_blank">{{berkas.judul_artikel}}</a></td>
                        {% if berkas.reviewer_2 == None %}
                          <td>Belum Ada</td>
                        {% elif berkas.reviewer_2 != None %}
                          <td>{{berkas.reviewer_2}}</td>
                        {% endif %}
                        <td>
                          {% if user.id == berkas.reviewer_2.reviewer.id %}
                            <a class="btn btn-primary" href="{% url 'penilaian:penilaian_prosiding2' berkas.pk %}">Nilai</a>
                            {% for berkus2 in list_berkas_2 %}
                              {% if berkas.id == berkus2.prosiding.id %}
                                <a class="btn btn-warning" href="{% url 'penilaian:edit_penilaian_prosiding2' berkas.slug %}">Edit</a>
                              {% endif %}
                            {% endfor %}
                          {% endif %}
                        <td>
                          {% for berkus2 in list_berkas_2 %}
                            {% if berkas.id == berkus2.prosiding.id %}
                              <button disabled type="button" class="btn btn-success">Sudah Dinilai</button>
                            {% endif %}
                          {% endfor %}
                        </td>
                    </tr>
                {% endif %}
                {% if user.is_superuser %}
                    <tr>
                        <td style="width: 30%;"><a href="{% url 'penilaian:detail_berkas_prosiding' berkas.pk%}" class="judul-artikel" target="_blank">{{berkas.judul_artikel}}</a></td>
                        <td>
                          {% if berkas.reviewer == None %}
                            Belum Ada
                          {% elif berkas.reviewer != None %}
                            {{berkas.reviewer}}
                          {% endif %}
                          {% if berkas.reviewer_2 == None %}
                            <br> Belum Ada
                          {% elif berkas.reviewer_2 != None %}
                            <br> {{berkas.reviewer_2}}
                          {% endif %}
                        </td>
                        <td>
                          {% if user.is_superuser %}
                            {% if berkas.reviewer != None %}
                              <a class="btn btn-primary" href="{% url 'penilaian:penilaian_prosiding' berkas.pk %}">Nilai</a>
                              {% for berkus in list_berkas %}
                                {% if berkas.id == berkus.prosiding.id %}
                                  <a class="btn btn-warning" href="{% url 'penilaian:edit_penilaian_prosiding' berkas.slug %}">Edit<a>
                                {% endif %}
                              {% endfor %}
                            {% endif %}
                            <div class="spacing"></div>
                            {% if berkas.reviewer_2 != None %}
                              <a class="btn btn-primary" href="{% url 'penilaian:penilaian_prosiding2' berkas.pk %}">Nilai</a>
                              {% for berkus2 in list_berkas_2 %}
                                {% if berkas.id == berkus2.prosiding.id %}
                                  <a class="btn btn-warning" href="{% url 'penilaian:edit_penilaian_prosiding2' berkas.slug %}">Edit</a>
                                {% endif %}
                              {% endfor %}
                            {% endif %}
                          {% endif %}
                        <td>
                          {% for berkus in list_berkas %}
                            {% if berkas.id == berkus.prosiding.id %}
                              <button disabled class="btn btn-success">Sudah Dinilai (R1)</button>
                            {% endif %}
                          {% endfor %}
                          <div class="spacing"></div>
                          {% for berkus2 in list_berkas_2 %}
                            {% if berkas.id == berkus2.prosiding.id %}
                              <button disabled class="btn btn-success">Sudah Dinilai (R2)</button>
                            {% endif %}
                          {% endfor %}
                        </td>
                    </tr>
                {% endif %}
              {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="pagination d-flex justify-content-center">
        {% if page_obj.has_previous %}
          <a href="{% url 'penilaian:list_penilaian_prosiding' page_obj.previous_page_number %}">&laquo;</a>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <span class="active">
              {{i}}
            </span>
          {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
            <a href="{% url 'penilaian:list_penilaian_prosiding' i %}">
              {{i}}
            </a>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <a href="{% url 'penilaian:list_penilaian_prosiding' page_obj.next_page_number %}">&raquo;</a>
        {% endif %}
      </div>
    </div>
    
      
    {% include 'snippets/script.html' %}
</body>
</html>