penilaian/urls.py
from os import name
from django.views.static import serve
from django.urls import path
from . import views
from webfisika import settings
from django.conf.urls.static import static

urlpatterns = [
    path('edit_data/<pk>/', views.EditDataDiriView.as_view(), name='edit_data'),
    ######### End Edit Data User #########
    path('upload_berkas_jurnal/', views.UploadBerkasJurnalView.as_view(), name='upload_berkas_jurnal'),
    path('upload_berkas_prosiding/', views.UploadBerkasProsidingView.as_view(), name='upload_berkas_prosiding'),
    path('upload_berkas_buku/', views.UploadBerkasBukuView.as_view(), name='upload_berkas_buku'),
    path('upload_berkas_haki/', views.UploadBerkasHakiView.as_view(), name='upload_berkas_haki'),
    ######### End Upload #########
    path('histori_pengajuan/jurnal/<page>/', views.ListBerkasJurnalView.as_view(), name='list_berkas_jurnal'),
    path('histori_pengajuan/prosiding/<page>/', views.ListBerkasProsidingView.as_view(), name='list_berkas_prosiding'),
    path('histori_pengajuan/buku/<page>/', views.ListBerkasBukuView.as_view(), name='list_berkas_buku'),
    path('histori_pengajuan/haki/<page>/', views.ListBerkasHakiView.as_view(), name='list_berkas_haki'),
    ######### End List Pengajuan #########
    path('histori_pengajuan/jurnal/detail/<pk>/', views.DetailBerkasJurnalView.as_view(), name='detail_berkas_jurnal'),
    path('histori_pengajuan/prosiding/detail/<pk>/', views.DetailBerkasProsidingView.as_view(), name='detail_berkas_prosiding'),
    path('histori_pengajuan/buku/detail/<pk>/', views.DetailBerkasBukuView.as_view(), name='detail_berkas_buku'),
    path('histori_pengajuan/haki/detail/<pk>/', views.DetailBerkasHakiView.as_view(), name='detail_berkas_haki'),
    ######### End Detail Berkas #########
    path('histori_pengajuan/jurnal/edit/<pk>/', views.EditBerkasJurnalView.as_view(), name='edit_berkas_jurnal'),
    path('histori_pengajuan/prosiding/edit/<pk>/', views.EditBerkasProsidingView.as_view(), name='edit_berkas_prosiding'),
    path('histori_pengajuan/buku/edit/<pk>/', views.EditBerkasBukuView.as_view(), name='edit_berkas_buku'),
    path('histori_pengajuan/haki/edit/<pk>/', views.EditBerkasHakiView.as_view(), name='edit_berkas_haki'),
    ######### End Edit Berkas #########
    path('histori_pengajuan/jurnal/plagiasi_linieritas/<pk>/', views.PlagiasiLinieritasView.as_view(), name='plagiasi'),
    path('histori_pengajuan/jurnal/plagiasi_linieritas/edit/<pk>/', views.EditPlagiasiLinieritasView.as_view(), name='edit_plagiasi'),
    path('histori_pengajuan/prosiding/plagiasi_linieritas/<pk>/', views.PlagiasiLinieritasProsidingView.as_view(), name='plagiasi_prosiding'),
    path('histori_pengajuan/prosiding/plagiasi_linieritas/edit/<pk>/', views.EditPlagiasiLinieritasProsidingView.as_view(), name='edit_plagiasi_prosiding'),
    ######### End Plagiasi #########
    path('histori_pengajuan/jurnal/verifikasi/<pk>/', views.VerifikasiBerkasJurnalView.as_view(), name='verifikasi_berkas_jurnal'),
    path('histori_pengajuan/prosiding/verifikasi/<pk>/', views.VerifikasiBerkasProsidingView.as_view(), name='verifikasi_berkas_prosiding'),
    path('histori_pengajuan/buku/verifikasi/<pk>/', views.VerifikasiBerkasBukuView.as_view(), name='verifikasi_berkas_buku'),
    path('histori_pengajuan/haki/verifikasi/<pk>/', views.VerifikasiBerkasHakiView.as_view(), name='verifikasi_berkas_haki'),
    ######### End Verifikasi Berkas #########
    # R1 #
    path('penilaian_jurnal/R1/<pk>/', views.PenilaianBerkasJurnalView.as_view(), name='penilaian_jurnal'),
    path('penilaian_prosiding/R1/<pk>/', views.PenilaianBerkasProsidingView.as_view(), name='penilaian_prosiding'),
    path('penilaian_buku/R1/<pk>/', views.PenilaianBerkasBukuView.as_view(), name='penilaian_buku'),
    path('penilaian_haki/R1/<pk>/', views.PenilaianBerkasHakiView.as_view(), name='penilaian_haki'),
    # R2 #
    path('penilaian_jurnal/R2/<pk>/', views.PenilaianBerkasJurnal2View.as_view(), name='penilaian_jurnal2'),
    path('penilaian_prosiding/R2/<pk>/', views.PenilaianBerkasProsiding2View.as_view(), name='penilaian_prosiding2'),
    path('penilaian_buku/R2/<pk>/', views.PenilaianBerkasBuku2View.as_view(), name='penilaian_buku2'),
    path('penilaian_haki/R2/<pk>/', views.PenilaianBerkasHaki2View.as_view(), name='penilaian_haki2'),
    ######### End Penilaian #########
    # R1 #
    path('rekap_jurnal/R1/<slug>/',views.HasilPenilaianJurnalView.as_view(), name='rekap_jurnal'),
    path('rekap_prosiding/R1/<slug>/',views.HasilPenilaianProsidingView.as_view(), name='rekap_prosiding'),
    path('rekap_buku/R1/<slug>/',views.HasilPenilaianBukuView.as_view(), name='rekap_buku'),
    path('rekap_haki/R1/<slug>/',views.HasilPenilaianHakiView.as_view(), name='rekap_haki'),
    # R2 #
    path('rekap_jurnal/R2/<slug>/',views.HasilPenilaianJurnal2View.as_view(), name='rekap_jurnal2'),
    path('rekap_prosiding/R2/<slug>/',views.HasilPenilaianProsiding2View.as_view(), name='rekap_prosiding2'),
    path('rekap_buku/R2/<slug>/',views.HasilPenilaianBuku2View.as_view(), name='rekap_buku2'),
    path('rekap_haki/R2/<slug>/',views.HasilPenilaianHaki2View.as_view(), name='rekap_haki2'),
    # Gabungan R1 dan R2 #
    path('rekap_jurnal/<slug>/', views.HasilPenilaianBerkasJurnalGabunganView.as_view(), name='gabungan_jurnal'),
    path('rekap_prosiding/<slug>/', views.HasilPenilaianBerkasProsidingGabunganView.as_view(), name='gabungan_prosiding'),
    path('rekap_buku/<slug>/', views.HasilPenilaianBerkasBukuGabunganView.as_view(), name='gabungan_buku'),
    path('rekap_haki/<slug>/', views.HasilPenilaianBerkasHakiGabunganView.as_view(), name='gabungan_haki'),
    ######### End of Hasil Rekap #########
    path('tambah_penulis/', views.PenulisLainView.as_view(), name='tambah_penulis'),
    ######### End of Tambah Penulis #########
    path('list_penilaian_jurnal/<page>/', views.ListReviewerJurnalView.as_view(), name='list_penilaian_jurnal'),
    path('list_penilaian_prosiding/<page>/', views.ListReviewerProsidingView.as_view(), name='list_penilaian_prosiding'),
    path('list_penilaian_buku/<page>/', views.ListReviewerBukuView.as_view(), name='list_penilaian_buku'),
    path('list_penilaian_haki/<page>/', views.ListReviewerHakiView.as_view(), name='list_penilaian_haki'),
    ######### End of Tabel Penilaian #########
    # R1 #
    path('penilaian_jurnal/edit/R1/<slug>/', views.PenilaianBerkasJurnalEditView.as_view(), name='edit_penilaian_jurnal'),
    path('penilaian_prosiding/edit/R1/<slug>/', views.PenilaianBerkasProsidingEditView.as_view(), name='edit_penilaian_prosiding'),
    path('penilaian_buku/edit/R1/<slug>/', views.PenilaianBerkasBukuEditView.as_view(), name='edit_penilaian_buku'),
    path('penilaian_haki/edit/R1/<slug>/', views.PenilaianBerkasHakiEditView.as_view(), name='edit_penilaian_haki'),
    # R2 #
    path('penilaian_jurnal/edit/R2/<slug>/', views.PenilaianBerkasJurnal2EditView.as_view(), name='edit_penilaian_jurnal2'),
    path('penilaian_prosiding/edit/R2/<slug>/', views.PenilaianBerkasProsiding2EditView.as_view(), name='edit_penilaian_prosiding2'),
    path('penilaian_buku/edit/R2/<slug>/', views.PenilaianBerkasBuku2EditView.as_view(), name='edit_penilaian_buku2'),
    path('penilaian_haki/edit/R2/<slug>/', views.PenilaianBerkasHaki2EditView.as_view(), name='edit_penilaian_haki2'),
    ######### End of Edit Penilaian #########
    path('error/penilaian_belum_ada', views.ErrorMessage.as_view(), name='error_message'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ubah_data_user/', views.UserEditView.as_view(), name='ubah_data_user'),
    path('signup/', views.UserRegisterView.as_view(), name='register'),
    path('password/', views.PasswordChangeView.as_view(), name='ubah_password'),   
]

webfisika/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexHomeView.as_view(), name='home'),
    # path('', views.ComingSoon.as_view(), name='home'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('success/', views.Success.as_view(), name = 'success'),
    path('penilaian/', include(('penilaian.urls', 'penilaian'), namespace='penilaian')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/snippets/modals_logout.html
<div class="modal fade" id="Logout" tabindex="-1" role="dialog" aria-labelledby="Logout" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Logout</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Yakin anda ingin logout?</p>
        </div>
        <div class="modal-footer">
          <form action="{% url 'logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" name="logout" value="Logout">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
          </form>
        </div>
      </div>
    </div>
  </div>

templates/snippets/navbar.html
<header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center">
      <img class="mr-auto" src="/assets/img/logo-unpad1.png" alt="" style="width: 60px;">
      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class=""><a href="{% url 'home' %}">Home</a></li>
          {% if user.is_authenticated %}
            <li class="drop-down"><a href="#">Pemberkasan</a>
              <ul>
                <li class="drop-down drop-down-deep"><a href="#">Upload Berkas</a>
                  <ul>
                    <li><a href="{% url 'penilaian:upload_berkas_jurnal' %}">Upload Berkas Jurnal</a></li>
                    <li><a href="{% url 'penilaian:upload_berkas_prosiding' %}">Upload Berkas Prosiding</a></li>
                    <li><a href="{% url 'penilaian:upload_berkas_buku' %}">Upload Berkas Buku</a></li>
                    <li><a href="{% url 'penilaian:upload_berkas_haki' %}">Upload Berkas HaKI</a></li>
                  </ul>
                </li>
                <div class="dropdown-divider"></div>
                <li><a href="{% url 'penilaian:list_berkas_jurnal' 1 %}">Riwayat Pengajuan</a></li>
                <li><a href="{% url 'penilaian:tambah_penulis' %}">Tambah Penulis Selain Dosen</a></li>
              </ul>
            </li>
            {% for group in user.groups.all %}
              {% if group.name == 'SuperAdmin' %}
                <li><a href="{% url 'penilaian:list_penilaian_jurnal' 1 %}">Tabel Penilaian</a></li>
              {% elif group.name == 'Reviewer' %}  
                <li><a href="{% url 'penilaian:list_penilaian_jurnal' 1 %}">Tabel Penilaian</a></li>
              {% endif %}
            {% endfor %}
          {% endif %}
          {% if user.is_authenticated %}
            <li class="drop-down"><a href="#"><strong>{{user.first_name}}</strong></a>
              <ul>
                <li><a href="{% url 'users:ubah_data_user' %}">Ubah Data User</a></li>
                <div class="dropdown-divider"></div>
                <!-- <li><a href="{% url 'logout' %}">Logout</a></li> -->
                <li><a href="#" data-toggle="modal" data-target="#Logout">Logout</a></li>
              </ul>
            </li>
          {% else %}
            <a href="{% url 'login' %}" class="get-started-btn scrollto">Login</a>
          {% endif %}
        </ul>       
      </nav><!-- .nav-menu -->
    </div>
</header><!-- End Header -->

{% include 'snippets/modals_logout.html' %}

templates/snippets/navbar_backup.html
<header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center">
      <img class="mr-auto" src="/assets/img/logo-unpad1.png" alt="" style="width: 60px;">
      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class=""><a href="{% url 'home' %}">Home</a></li>
          {% if user.is_authenticated %}
            <li class="drop-down"><a href="#">Pemberkasan</a>
              <ul>
                <li class="drop-down drop-down-deep"><a href="#">Upload Berkas</a>
                  <ul>
                    <li><a href="{% url 'penilaian:upload_berkas_jurnal' %}">Upload Berkas Jurnal</a></li>
                    <li><a href="{% url 'penilaian:upload_berkas_prosiding' %}">Upload Berkas Prosiding</a></li>
                    <li><a href="{% url 'penilaian:upload_berkas_buku' %}">Upload Berkas Buku</a></li>
                    <li><a href="{% url 'penilaian:upload_berkas_haki' %}">Upload Berkas HaKI</a></li>
                  </ul>
                </li>
                <div class="dropdown-divider"></div>
                <li><a href="{% url 'penilaian:list_berkas_jurnal' %}">Histori Pengajuan</a></li>
                <li><a href="{% url 'penilaian:tambah_penulis' %}">Tambah Penulis Selain Dosen</a></li>
              </ul>
            </li>
            
            {% for group in user.groups.all %}
              {% if group.name == 'SuperAdmin' %}
                <li class="drop-down"><a href="#">Penilaian</a>
                  <ul>
                    <li><a href="{% url 'penilaian:penilaian_jurnal' %}">Penilaian Jurnal</a></li>
                    <li><a href="{% url 'penilaian:penilaian_prosiding' %}">Penilaian Prosiding</a></li>
                    <li><a href="{% url 'penilaian:penilaian_buku' %}">Penilaian Buku</a></li>
                    <li><a href="{% url 'penilaian:penilaian_haki' %}">Penilaian Haki</a></li>
                    <div class="dropdown-divider"></div>
                    <li><a href="{% url 'penilaian:list_penilaian_jurnal' %}">Tabel Penilaian</a></li>
                  </ul>
                </li>
              {% elif group.name == 'Reviewer' %}  
                <li class="drop-down"><a href="#">Penilaian</a>
                  <ul>
                    <li><a href="{% url 'penilaian:penilaian_jurnal' %}">Penilaian Jurnal</a></li>
                    <li><a href="{% url 'penilaian:penilaian_prosiding' %}">Penilaian Prosiding</a></li>
                    <li><a href="{% url 'penilaian:penilaian_buku' %}">Penilaian Buku</a></li>
                    <li><a href="{% url 'penilaian:penilaian_haki' %}">Penilaian Haki</a></li>
                    <div class="dropdown-divider"></div>
                    <li><a href="{% url 'penilaian:list_penilaian_jurnal' %}">Tabel Penilaian</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endfor %}
          {% endif %}
          {% if user.is_authenticated %}
            <li class="drop-down"><a href="#"><strong>{{user.first_name}}</strong></a>
              <ul>
                <li><a href="{% url 'users:ubah_data_user' %}">Ubah Data User</a></li>
                <div class="dropdown-divider"></div>
                <!-- <li><a href="{% url 'logout' %}">Logout</a></li> -->
                <li><a href="#" data-toggle="modal" data-target="#Logout">Logout</a></li>
              </ul>
            </li>
          {% else %}
            <a href="{% url 'login' %}" class="get-started-btn scrollto">Login</a>
          {% endif %}
        </ul>       
      </nav><!-- .nav-menu -->
    </div>
</header><!-- End Header -->

{% include 'snippets/modals_logout.html' %}

templates/snippets/script.html
<!-- Vendor JS Files -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="/assets/vendor/jquery/jquery.min.js" type="text/javascript"></script>
<script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js" type="text/javascript"></script>
<script src="/assets/vendor/jquery.easing/jquery.easing.min.js" type="text/javascript"></script>
<script src="/assets/vendor/php-email-form/validate.js" type="text/javascript"></script>
<script src="/assets/vendor/waypoints/jquery.waypoints.min.js" type="text/javascript"></script>
<script src="/assets/vendor/isotope-layout/isotope.pkgd.min.js" type="text/javascript"></script>
<script src="/assets/vendor/venobox/venobox.min.js" type="text/javascript"></script>
<script src="/assets/vendor/owl.carousel/owl.carousel.min.js" type="text/javascript"></script>
<script src="/assets/vendor/aos/aos.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>


<!-- Template Main JS File -->
<script src="/assets/js/main.js" type="text/javascript"></script>

templates/snippets/style.html
<!-- Favicons -->
<link href="/assets/img/logo-unpad1.png" rel="icon">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/assets/vendor/icofont/icofont.min.css" rel="stylesheet" type="text/css">
<link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" type="text/css">
<link href="/assets/vendor/remixicon/remixicon.css" rel="stylesheet" type="text/css">
<link href="/assets/vendor/venobox/venobox.css" rel="stylesheet" type="text/css">
<link href="/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet" type="text/css">
<link href="/assets/vendor/aos/aos.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css">

<!-- Template Main CSS File -->
<link href="/assets/css/style.css" rel="stylesheet" type="text/css">