users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ubah_data_user/', views.UserEditView.as_view(), name='ubah_data_user'),
    path('signup/', views.UserRegisterView.as_view(), name='register'),
    path('password/', views.PasswordChangeView.as_view(), name='ubah_password'),   
]

webfisika/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexHomeView.as_view(), name='home'),
    # path('', views.ComingSoon.as_view(), name='home'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('success/', views.Success.as_view(), name = 'success'),
    path('penilaian/', include(('penilaian.urls', 'penilaian'), namespace='penilaian')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, PasswordChangeForm
    
class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput)
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'email',
            'password1',
            'password2'
        ]
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
    
class EditProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput)
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'email',
            'password',
        ]

class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'type':'password'}))
    new_password1 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'type':'password'}))
    new_password2 = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'type':'password'}))
    class Meta:
        model = User
        fields = [
            'old_password',
            'new_password1',
            'new_password2'
        ]
    def __init__(self, *args, **kwargs):
        super(PasswordChangingForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = "Password Lama"
        self.fields['new_password1'].label = "Password Baru"
        self.fields['new_password2'].label = "Konfirmasi Password Baru"

users/views.py
# from django.contrib.auth.forms import PasswordChangeForm
from .forms import EditProfileForm, PasswordChangingForm, SignUpForm
from django.shortcuts import redirect, render
from django.views.generic import UpdateView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.models import Group
from django.contrib.messages.views import SuccessMessageMixin
# Create your views here.

class PasswordChangeView(SuccessMessageMixin,PasswordChangeView):
    form_class = PasswordChangingForm
    template_name = 'users/ubah_password.html'
    success_url = reverse_lazy('home')
    success_message = 'Password Berhasil Diubah!'

class UserRegisterView(CreateView):
    form_class = SignUpForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('login')
    def post(self, request, *args, **kwargs):
        pass
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            user_group = Group.objects.get(name='User')
            user.groups.add(user_group)
            return redirect('login')
        else:
            return render(request, self.template_name, {'form' : form })

class UserEditView(UpdateView):
    form_class = EditProfileForm
    template_name = 'users/ubah_data_user.html'
    success_url = reverse_lazy('home')
    def get_object(self):
        return self.request.user

users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SignUp</title>
    {% include 'snippets/style.html' %}
</head>
<body>
    {% include 'snippets/navbar.html' %}
    <section id="portfolio" class="portfolio">
        <br>
        <div class="section-title" data-aos="zoom-in">
            <h2 class="text-white">Register User</h2>
        </div>
        <div class="container d-flex justify-content-center" data-aos="zoom-in">
            <div class="card">
                <article class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <p><label for="id_username">Nomor Induk Pegawai:</label> <input type="text" name="username" maxlength="150" autofocus class="form-control" required id="id_username"> <span class="helptext">Isi dengan nomor induk pegawai.</span></p>
                        <p><label for="id_first_name">Nama:</label> <input type="text" name="first_name" class="form-control" maxlength="100" required id="id_first_name"></p>
                        <p><label for="id_email">Email:</label> <input type="email" name="email" class="form-control" required id="id_email"></p>
                        <p><label for="id_password1">Password:</label> <input type="password" name="password1" autocomplete="new-password" class="form-control" required id="id_password1"> <span class="helptext"><ul><li>Kata sandi Anda tidak boleh terlalu mirip dengan informasi pribadi Anda yang lain.</li><li>Kata sandi Anda harus terdiri dari setidaknya 8 karakter.</li><li>Sandi Anda tidak boleh menjadi sandi yang biasa digunakan.</li><li>Sandi Anda tidak boleh seluruhnya berupa angka.</li></ul></span></p>
                        <p><label for="id_password2">Konfirmasi Password</label> <input type="password" name="password2" autocomplete="new-password" class="form-control" required id="id_password2"> <span class="helptext"><small>Masukkan kata sandi yang sama seperti sebelumnya, untuk verifikasi.</small></span></p>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Buat User </button>
                        </div> 
                    </form>
                </article>
            </div>
        </div>    
    </section>
    {% include 'snippets/script.html' %}
</body>
</html>

users/templates/users/ubah_data_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ubah Data User</title>
    {% include 'snippets/style.html' %}
</head>
<body>
    {% include 'snippets/navbar.html' %}
    <section id="portfolio" class="portfolio login">
        <br>
        <div class="section-title" data-aos="zoom-in">
            <h2 class="text-white">Ubah Profil</h2>
        </div>
        <div class="container d-flex justify-content-center" data-aos="zoom-in">
            <div class="card">
                <article class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <p><label for="{{form.username.id_for_label}}">Nomor Induk Pegawai:</label> <input type="text" name="{{form.username.name}}" value="{{form.username.value}}" class="form-control" maxlength="100" required id="{{form.username.id_for_label}}"></p>
                        <p><label for="{{form.first_name.id_for_label}}">Nama:</label> <input type="text" name="{{form.first_name.name}}" value="{{form.first_name.value}}" class="form-control" maxlength="100" required id="{{form.first_name.id_for_label}}"></p>
                        <p><label for="{{form.email.id_for_label}}">Email:</label> <input type="email" class="form-control" name="{{form.email.name}}" value="{{form.email.value}}" required id="{{form.email.id_for_label}}"></p>
                        <p><label>Password:</label><a href="{% url 'users:ubah_password' %}">&emsp;Ubah Password</a></p>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Update  </button>
                        </div> 
                    </form>
                </article>
            </div>
        </div>    
    </section>

    {% include 'snippets/script.html' %}
</body>
</html>

users/templates/users/ubah_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ubah Password</title>
    {% include 'snippets/style.html' %}
</head>
<body>
    {% include 'snippets/navbar.html' %}
    <section id="portfolio" class="portfolio">
        <br>
        <div class="section-title" data-aos="zoom-in">
            <h2 class="text-white">Ubah Password</h2>
        </div>
        <div class="container d-flex justify-content-center" data-aos="zoom-in">
            <div class="card">
                <article class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <div class="container"><small><li>Kata sandi Anda tidak boleh terlalu mirip dengan informasi pribadi Anda yang lain.</li><li>Kata sandi Anda harus terdiri dari setidaknya 8 karakter.</li><li>Sandi Anda tidak boleh menjadi sandi yang biasa digunakan.</li><li>Sandi Anda tidak boleh seluruhnya berupa angka.</li></ul></small></span></div>
                        <br>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Ubah Password  </button>
                        </div> <!-- form-group// -->
                    </form>
                </article>
            </div>
        </div>    
    </section>

    {% include 'snippets/script.html' %}
</body>
</html>